commands:
  docker-tag:
    description: "Add a new tag to a docker image that has already been pulled"
    parameters:
      from_tag:
        type: string
        default: $CIRCLE_SHA1
      to_tag:
        type: string
        default: "master"
      image:
        type: string
    steps:
      - run: >
          docker tag <<parameters.image>>:<<parameters.from_tag>> <<parameters.image>>:<<parameters.to_tag>>

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: yalelibraryit/dc-iiif-cantaloupe
          cache_from: yalelibraryit/dc-iiif-cantaloupe:master
      - docker/push:
          image: yalelibraryit/dc-iiif-cantaloupe

  publish-latest:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - docker/check
      - docker/pull:
          images: yalelibraryit/dc-iiif-cantaloupe:$CIRCLE_SHA1
      - run: |
          echo "export CLEAN_BRANCH=`echo $CIRCLE_BRANCH |sed 's#[^[:alnum:]._-]##g'`" >> $BASH_ENV
      - docker-tag:
          image: yalelibraryit/dc-iiif-cantaloupe
          from_tag: $CIRCLE_SHA1
          to_tag: $CLEAN_BRANCH
      - docker/push:
          image: yalelibraryit/dc-iiif-cantaloupe
          tag: $CIRCLE_BRANCH
  publish-github-release:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - docker/check
      - docker/pull:
          images: yalelibraryit/dc-iiif-cantaloupe:$CIRCLE_SHA1
      - docker-tag:
          image: yalelibraryit/dc-iiif-cantaloupe
          from_tag: $CIRCLE_SHA1
          to_tag: $CIRCLE_TAG
      - docker/push:
          image: yalelibraryit/dc-iiif-cantaloupe
          tag: $CIRCLE_TAG


orbs:
  docker: circleci/docker@1.0.1
version: 2.1
workflows:
  commit:
    jobs:
      - build-and-push:
          context: yul-dc
      - publish-latest:
          context: yul-dc
          requires:
            - build-and-push
      - publish-github-release:
          context: yul-dc
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
